### ISSUE TITLE
How do you "add or increment" ?

### ISSUE THREAD

**Issue by AoDev** [mlomb/redis-rank#1]
Hello, 

Your lib is interesting and I am evaluating if I could use it for our project. 
One thing I am not sure how to do from the docs is to `add a new entry if it does not exist or increment the score of that entry if it does`? Would I need to `peek()` then decide `add / increment` or is there a better solution?

**Comment by mlomb** [comment]
Hi AoDev, `incr` would do what you need, it will increment the score of an entry by an amount, but if the entry doesn't exists it is created with the provided amount.

Here are snippets to relevant functions:
`add`: https://github.com/mlomb/redis-rank/blob/70f8d899487f4aeaa03a7a9d218ab0b86bea20c9/src/Leaderboard.ts#L53-L56
`incr`: https://github.com/mlomb/redis-rank/blob/70f8d899487f4aeaa03a7a9d218ab0b86bea20c9/src/Leaderboard.ts#L91-L96
You can also check `improve`: https://github.com/mlomb/redis-rank/blob/70f8d899487f4aeaa03a7a9d218ab0b86bea20c9/src/Leaderboard.ts#L69-L77

This matches the behaviour you expect?

**Comment by AoDev** [comment]
Thanks for the quick reply. Yes it seems to do what I need. I don't know Redis much,  so I checked what `zincrby` (in `incr`) does. Your lib is a good abstraction, I think you could add in the docs that `incr` will create a new entry if it does not exist.

----

As a side note (maybe I'll open another issue), I am interested in being able to save the leaderboard to another DB and you mention this in the readme.

> PLANNED: Archive (export) leaderboards to another database for long-term storage

Can I help you?

**Comment by mlomb** [comment]
I added a note in the README, please create another issue for the DB export.
