### ISSUE TITLE
[FEATURE]: Ability to set up a function to run at the end of each periodic leaderboard for example, for rewards to be distributed

### ISSUE THREAD

**Issue by LucaJeevanjee** [mlomb/redis-rank#10]

**Comment by mlomb** [comment]
Hi, sorry for the delay.
This is something you will have to handle yourself. You can have a cron job to check wether the current periodic key is different from the previous one, run the function, and mark somewhere that it finished.
You have to make sure that the function is faster than the periodic interval and do not start the function if it is already running but havent finished. Also what to do in case it fails: do you retry? what if one key was skipped?
And more things that don't come to mind right now, are very tied to your product so `redis-rank` should stay agnostic.
