### ISSUE TITLE
BUG: leaderboard creation not working

### ISSUE THREAD

**Issue by LucaJeevanjee** [mlomb/redis-rank#11]
I have recently changed my leaderboard update policy in my backend to 'aggregate' from 'replace'.
'replace' was working fine but was confusing to use as it required me fetching and updating myself instead of just sending a new value to be added.
however, since i have switched to 'aggregate' i have noticed that the leaderboards are not being created. at first i didn't notice this due to the cycle not ending but now i have just tested on a minute cycle and seen it.
I've just switched back to 'replace' and found that this isn't working either.

```
const periodicOptions: PeriodicLeaderboardOptions = {
        leaderboardOptions: {
            sortPolicy: 'high-to-low',
            updatePolicy: 'aggregate',
        },
        cycle: 'minute', // Update monthly
    };

    // Create a periodic leaderboard
    plb = new PeriodicLeaderboard(redisClient, 'gutz_monthly_leaderboard_m_test', periodicOptions);

    await redisClient.connect();    
```

**Comment by mlomb** [comment]
Hey!

> 'replace' was working fine but was confusing to use as it required me fetching and updating myself instead of just sending a new value to be added.

For that case you would use 'aggregate' right? Why did you switch?
Also be careful with race conditions.

> i have noticed that the leaderboards are not being created

What do you mean the leaderboards are not being created? It will create the key once you insert at least one entry.
Are you trying to insert but it is not being created?

**Comment by mlomb** [comment]
Closing due inactivity, feel free to reopen
