### ISSUE TITLE
Feature request: allow to store and retrieve arbitrary data for each member

### ISSUE THREAD

**Issue by AoDev** [mlomb/redis-rank#2]
Sometimes we need additional data about users in the leaderboard. 

Following the [redis docs about leaderboards](https://redislabs.com/redis-enterprise/use-cases/leaderboards/).

The first problem that comes to mind is that the `username` may not be a good ID for the leaderboard if users can change it. Especially if we go for longer periods like weekly leaderboards.

So we need a constant ID and a "screenname". 
In the Redis docs, they create an additional hash for each user with the needed properties. What they don't explain is how to best "join" the data.

I am interested in replicating this in __redis-rank__. Is this something you'd agree to have? I'd like to help as much as I can (I don't know much Redis)

**Comment by mlomb** [comment]
They way to go is to store unique user IDs in the leaderboard and then retrive the data from another database. You could use the same redis database to store the user data, but I prefer a relational database or alike to ensure data consistency.

**Comment by AoDev** [comment]
I understand this but I was asking if we could have this as a feature of this library to already have it in Redis.
So for example we could do `lb.incr('userId', 10, {screenName: 'redis-rank'})`

**Comment by mlomb** [comment]
I don't want to add that overload to the library. I think you could just do `lb.incr('userId', 10)` and then `redis_client.set('customdata:userId', {screenName: 'redis-rank'})` and don't involve the library at all.
You could even use `lb.incrMulti('userId', 10)` which returns a `IORedis.Pipeline` that you can chain with the set to make only one round trip to Redis.
The library shouldn't be responsible about the user data.

**Comment by AoDev** [comment]
I understand, thank you.
