### ISSUE TITLE
[bug] scores are turned into integers

### ISSUE THREAD

**Issue by AoDev** [mlomb/redis-rank#3]
A bit everywhere in the code, `parseInt` is used on scores. It leads to wrong results with decimal values.

2 examples:
* [Leaderboard.ts list](https://github.com/mlomb/redis-rank/blob/master/src/Leaderboard.ts#L175)
* [Leaderboard.ts incr](https://github.com/mlomb/redis-rank/blob/master/src/Leaderboard.ts#L98)
This one tricked me because`parseInt` is applied on the returned value. So the value in Redis is correctly increased but the returned value is wrong if it has decimals.

I suppose replacing `parseInt` by `parseFloat` everywhere would do the trick but maybe you had a reason.

**Comment by mlomb** [comment]
You were right, thanks for the report. I've changed the `parseInt` to `parseFloat` where needed and added a few tests.
