### ISSUE TITLE
Reverse Lookup: Find nearby users with a particular score

### ISSUE THREAD

**Issue by Energy0124** [mlomb/redis-rank#6]
I am looking for a way to find users within a score range. Is there a way to do it with this library?
One of the use cases is matchmaking. Given a skill rating, I would like to find players with a similar skill rating.
If there is no way to do it currently, do you have a plan to implement this feature?

I find that Redis support ZRANGE BYSCORE, which means this should be relatively easy to implement. I could try to implement it and submit a PR.

**Comment by mlomb** [comment]
I think this is a good use case.
As I understand, you will mantain a leaderboard for the people in queue.
Altough not the same, [around](https://github.com/mlomb/redis-rank/blob/master/docs/Leaderboard.md#list-entries) can find entries nearby another by score (but querying by ID).

**Comment by Energy0124** [comment]
In my use case `around` would not work as I have to query by score. Basically each user will have 2 rating, attack rating and defense rating. During matchmaking, I have to find a opponent with the closest defense rating to the current user's attack rating, so I have to query by the attack rating(by score). 

I actually add 'query by score' in my forked version, but I am not sure if it meets your coding standard. Maybe I will submit a PR first and see if you are OK with it.
